<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Media extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'user_id',
        'disk',
        'directory',
        'filename',
        'original_filename',
        'mime_type',
        'extension',
        'size',
        'width',
        'height',
        'type',
        'alt',
        'title',
        'caption',
        'description',
        'metadata',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'size' => 'integer',
        'width' => 'integer',
        'height' => 'integer',
        'metadata' => 'json',
    ];

    /**
     * Get the user that uploaded the media.
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Get the full URL for the media file.
     */
    public function getUrlAttribute(): string
    {
        return Storage::disk($this->disk)->url($this->directory.'/'.$this->filename);
    }

    /**
     * Get the thumbnail URL for the media file.
     */
    public function getThumbnailUrlAttribute(): string
    {
        $thumbnailPath = $this->directory.'/thumbnails/'.$this->filename;

        if (Storage::disk($this->disk)->exists($thumbnailPath)) {
            return Storage::disk($this->disk)->url($thumbnailPath);
        }

        return $this->url;
    }

    // ─────────────────────────────────────────────────────────────────────
    // Responsive variants (generated by ImageVariantService)
    // ─────────────────────────────────────────────────────────────────────

    /**
     * Responsive variant metadata recorded by ImageVariantService.
     *
     * Shape: ['original' => [...entries], 'webp' => [...], 'avif' => [...]]
     * where every entry is {width, height, size, url, path}.
     *
     * @return array<string, array<int, array<string, int|string>>>
     */
    public function variants(): array
    {
        $variants = $this->metadata['variants'] ?? null;

        return is_array($variants) ? $variants : [];
    }

    /**
     * Whether responsive variants have been generated for this media.
     */
    public function hasVariants(): bool
    {
        return $this->variants() !== [];
    }

    /**
     * Build a `srcset` value for one variant group, sorted by width.
     *
     * @param  string  $group  'original' | 'webp' | 'avif'
     */
    public function srcsetFor(string $group = 'original'): string
    {
        $entries = $this->variants()[$group] ?? [];
        if (! is_array($entries) || $entries === []) {
            return '';
        }

        return collect($entries)
            ->filter(fn ($e) => is_array($e) && ! empty($e['url']) && ! empty($e['width']))
            ->sortBy(fn (array $e) => (int) $e['width'])
            ->map(fn (array $e) => $e['url'].' '.$e['width'].'w')
            ->implode(', ');
    }

    /**
     * Delete the media file from storage.
     */
    public function deleteFile(): void
    {
        if (Storage::disk($this->disk)->exists($this->directory.'/'.$this->filename)) {
            Storage::disk($this->disk)->delete($this->directory.'/'.$this->filename);
        }

        // Delete thumbnail if exists
        $thumbnailPath = $this->directory.'/thumbnails/'.$this->filename;
        if (Storage::disk($this->disk)->exists($thumbnailPath)) {
            Storage::disk($this->disk)->delete($thumbnailPath);
        }

        // Delete generated responsive variants (best-effort).
        foreach ($this->variants() as $entries) {
            if (! is_array($entries)) {
                continue;
            }
            foreach ($entries as $entry) {
                $path = is_array($entry) ? ($entry['path'] ?? null) : null;
                if (is_string($path) && $path !== '' && Storage::disk($this->disk)->exists($path)) {
                    Storage::disk($this->disk)->delete($path);
                }
            }
        }
    }
}
